name: Build VSCode extension Preview 

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn package
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: "YYYYMMDDhhmmss"
          utcOffset: "+08:00"
      - uses: "marvinpinto/action-automatic-releases@latest"
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          automatic_release_tag: "latest"
          title: "Build ${{ steps.current-time.outputs.formattedTime }}"
          files: |
            *.vsix
